### ISSUE TITLE
Invalid Ethereum Adress

### ISSUE THREAD

**Issue by Noflare** [vieiraricardo/auto-matic#1]
Hello, every time I launch the bot it tells me : 
"define a valid ethereum address"

the command I executed : 
"auto matic 0xa9EB4e35FF8C999D2277237014b65259E2F254A6"

**Comment by vieiraricardo** [comment]
> Hello, every time I launch the bot it tells me : "define a valid ethereum address"
> 
> the command I executed : "auto matic 0xa9EB4e35FF8C999D2277237014b65259E2F254A6"

sorry for that, I was going to fix this problem but I'm going to archive the repository because the api I used to get the faucets doesn't work anymore
